spring.application.name=filmsAPI
spring.datasource.url=jdbc:postgresql://localhost:5432/films
spring.datasource.username=postgres
spring.datasource.password=1

spring.datasource.hikari.connection-timeout=10000
spring.datasource.hikari.initialization-fail-timeout=10000

spring.sql.init.mode=always
spring.jooq.sql-dialect=POSTGRES